services:
  db:
    image: postgres:17-alpine
    container_name: hh_ping_pong_db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pingpong
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    container_name: hh_pingpong_django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: pingpong
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    command: > 
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:

